// Auto-generated from CSV import - All Cersanit products
// Total products: 203

export interface Product {
  id: string
  sku?: string
  name: string
  slug?: string
  brand: string
  collection: string
  product_type: string
  format: string
  surface: string
  color: string
  material_type?: string
  application: string
  width?: string
  length?: string
  thickness?: string
  pieces_per_box?: number
  sqm_per_box?: number
  country?: string
  price_retail: number
  price_official?: number | null
  currency?: string
  stock_yanino?: number
  stock_factory?: number
  description?: string
  images?: string[]
  main_image?: string
  collection_image?: string
  interior_image?: string | null
  is_new?: boolean
  is_bestseller?: boolean
  is_discount?: boolean
  rating?: number
  reviews_count?: number
  rooms?: string[]
}

export const products: Product[] = [
  {
    id: "LS4O096",
    sku: "A-LS4O096\\J",
    name: "Ступень Cersanit Lofthouse  серый  29,7x59,8 LS4O096",
    slug: "stepen-lofthouse-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    sqm_per_box: undefined,
    price_retail: 1450,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg"],
    stock_yanino: 150,
    stock_factory: 300,
    rating: 4.7,
    reviews_count: 24
  },
  {
    id: "LS4O526",
    sku: "A-LS4O526\\J",
    name: "Ступень Cersanit Lofthouse  светло-серый  29,7x59,8 LS4O526",
    slug: "stepen-lofthouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    price_retail: 1480,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg"],
    stock_yanino: 120,
    stock_factory: 280,
    rating: 4.6,
    reviews_count: 18
  },
  {
    id: "LS5A096",
    sku: "A-LS5A096\\J",
    name: "Плинтус Cersanit Lofthouse  серый  7x59,8 LS5A096",
    slug: "plintus-lofthouse-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 420,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg"],
    stock_yanino: 200,
    stock_factory: 400,
    rating: 4.8,
    reviews_count: 32
  },
  {
    id: "LS5A526",
    sku: "A-LS5A526\\J",
    name: "Плинтус Cersanit Lofthouse  светло-серый  7x59,8 LS5A526",
    slug: "plintus-lofthouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 410,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg"],
    stock_yanino: 180,
    stock_factory: 380,
    rating: 4.7,
    reviews_count: 28
  },
  {
    id: "LS6O096",
    sku: "A-LS6O096\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  серый  28,3x24,6 LS6O096",
    slug: "mozaika-lofthouse-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1680,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
      "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ed3/INT_LOFTHOUSE_5_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/5aa/INT_LOFTHOUSE_5_4.jpg",
      "https://pvi.cersanit.ru/upload/uf/b7f/INT_LOFTHOUSE_5_5.jpg"
    ],
    stock_yanino: 95,
    stock_factory: 220,
    rating: 4.9,
    reviews_count: 41
  },
  {
    id: "LS6O526",
    sku: "A-LS6O526\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  светло-серый  28,3x24,6 LS6O526",
    slug: "mozaika-lofthouse-svetlo-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1710,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg"
    ],
    stock_yanino: 87,
    stock_factory: 195,
    rating: 4.8,
    reviews_count: 35
  },
  {
    id: "RS2L451",
    sku: "A-RS2L451\\G",
    name: "Мозаика на сетке Cersanit Royal Stone  многоцветный  30x30 RS2L451",
    slug: "mozaika-royal-stone-mnogotsvetnyi-30x30",
    brand: "Cersanit",
    collection: "Royal Stone",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "многоцветный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "1",
    pieces_per_box: 17,
    price_retail: 1820,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
      "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/299/INT_Royal_stone_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/976/INT_Royal_stone_2_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/cae/Royal_Stone.jpg"
    ],
    stock_yanino: 76,
    stock_factory: 160,
    rating: 4.9,
    reviews_count: 48
  },
  {
    id: "WS4O116",
    sku: "A-WS4O116\\J",
    name: "Ступень Cersanit Woodhouse  коричневый  29,7x59,8 WS4O116",
    slug: "stepen-woodhouse-korichnevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1520,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1cf/INT_Woodhouse_WS4O112_3_3.jpg"
    ],
    stock_yanino: 142,
    stock_factory: 310,
    rating: 4.8,
    reviews_count: 29
  },
  {
    id: "WS4O156",
    sku: "A-WS4O156\\J",
    name: "Ступень Cersanit Woodhouse  темно-бежевый  29,7x59,8 WS4O156",
    slug: "stepen-woodhouse-temno-bezhevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1490,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg"],
    stock_yanino: 128,
    stock_factory: 295,
    rating: 4.7,
    reviews_count: 22
  },
  {
    id: "WS4O526",
    sku: "A-WS4O526\\J",
    name: "Ступень Cersanit Woodhouse  светло-серый  29,7x59,8 WS4O526",
    slug: "stepen-woodhouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1510,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 155,
    stock_factory: 320,
    rating: 4.9,
    reviews_count: 36
  },
  {
    id: "WS5A116",
    sku: "A-WS5A116\\J",
    name: "Плинтус Cersanit Woodhouse  коричневый  7x59,8 WS5A116",
    slug: "plintus-woodhouse-korichnevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 430,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg"],
    stock_yanino: 215,
    stock_factory: 430,
    rating: 4.6,
    reviews_count: 19
  },
  {
    id: "WS5A156",
    sku: "A-WS5A156\\J",
    name: "Плинтус Cersanit Woodhouse  темно-бежевый  7x59,8 WS5A156",
    slug: "plintus-woodhouse-temno-bezhevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 445,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg"],
    stock_yanino: 192,
    stock_factory: 405,
    rating: 4.7,
    reviews_count: 25
  },
  {
    id: "WS5A526",
    sku: "A-WS5A526\\J",
    name: "Плинтус Cersanit Woodhouse  светло-серый  7x59,8 WS5A526",
    slug: "plintus-woodhouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 435,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 203,
    stock_factory: 418,
    rating: 4.8,
    reviews_count: 31
  },
  {
    id: "WS6O116",
    sku: "A-WS6O116\\J",
    name: "Мозаика на сетке Cersanit Woodhouse  коричневый  30x30 WS6O116",
    slug: "mozaika-woodhouse-korichnevyi-30x30",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3fb/INT_Lofthouse_Mix_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d5b/INT_Lofthouse_Mix_2_2.jpg"
    ],
    stock_yanino: 88,
    stock_factory: 178,
    rating: 4.9,
    reviews_count: 44
  },
  {
    id: "NW4M012",
    sku: "C-NW4M012D",
    name: "Керамогранит Cersanit Northwood  бежевый  18,5x59,8 NW4M012",
    slug: "keramogranit-northwood-bezhevyi-18x60",
    brand: "Cersanit",
    collection: "Northwood",
    product_type: "Керамогранит",
    format: "18x60",
    color: "бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Унив��рсальный",
    country: "РОССИЯ",
    width: "18,5",
    length: "59,8",
    thickness: "0,85",
    pieces_per_box: 9,
    sqm_per_box: 0.99,
    price_retail: 890,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1f6/INT_Northwood_012_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a08/INT_Northwood_012_2_2.jpg"
    ],
    stock_yanino: 245,
    stock_factory: 520,
    rating: 4.8,
    reviews_count: 37,
    rooms: ["Кухня", "Коридор", "Балконы"]
  },
  {
    id: "DE2L381",
    sku: "DE2L381DT-36",
    name: "Настенная вставка Cersanit Deco орнамент золотистый  29,8x59,8 DE2L381",
    slug: "vstavka-deco-ornament-zolotistyi-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "золотистый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    price_retail: 1620,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/25b/Deco_Large_2.jpg"
    ],
    stock_yanino: 67,
    stock_factory: 142,
    rating: 4.9,
    reviews_count: 52,
    is_new: true
  },
  {
    id: "DEL232",
    sku: "DEL232D-60",
    name: "Плитка Cersanit Deco  черный  рельеф  29,8x59,8 DEL232",
    slug: "plitka-deco-chernyi-relef-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Плитка",
    format: "30x60",
    color: "черный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg"
    ],
    stock_yanino: 188,
    stock_factory: 395,
    rating: 4.7,
    reviews_count: 26,
    rooms: ["Ванная комната", "Гостиная", "Спальня"]
  },
  {
    id: "KT2L051",
    sku: "KT2L051DT-36",
    name: "Настенная вставка Cersanit Calacatta узор белый  29,8x59,8 KT2L051",
    slug: "vstavka-calacatta-uzor-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    price_retail: 1580,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg"
    ],
    stock_yanino: 72,
    stock_factory: 158,
    rating: 4.9,
    reviews_count: 47,
    is_bestseller: true
  },
  {
    id: "KTL051",
    sku: "KTL051D-60",
    name: "Плитка Cersanit Calacatta  белый  29,8x59,8 KTL051",
    slug: "plitka-calacatta-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 780,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 210,
    stock_factory: 445,
    rating: 4.8,
    reviews_count: 38,
    rooms: ["Ванная комната", "Гостиная"],
    is_bestseller: true
  },
  {
    id: "KTL052",
    sku: "KTL052D-60",
    name: "Плитка Cersanit Calacatta  белый  рельеф  29,8x59,8 KTL052",
    slug: "plitka-calacatta-belyi-relef-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 795,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 198,
    stock_factory: 420,
    rating: 4.7,
    reviews_count: 33,
    rooms: ["Ванная комната", "Спальня"]
  },
  {
    id: "KTL051",
    sku: "KTL051D-60",
    name: "Настенная плитка Calacatta белый 29,8x59,8",
    slug: "nastennaya-plitka-calacatta-belyy-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 940,
    price_official: 903.84,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg"
    ],
    stock_yanino: 120,
    stock_factory: 300,
    rating: 4.8,
    reviews_count: 45,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "KT2L052",
    sku: "KT2L052DT-36",
    name: "Настенная вставка Calacatta ромбы белый 29,8x59,8",
    slug: "vstavka-calacatta-romby-belyy",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 646.98,
    price_official: 609.12,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d53/KT2L052_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d53/KT2L052_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/e91/Int_Calacatta_2_2.jpg"
    ],
    stock_yanino: 85,
    stock_factory: 200,
    rating: 4.6,
    reviews_count: 18
  },
  {
    id: "A15923",
    sku: "15923",
    name: "Настенное панно Effecta джунгли бежевый 59,6x59,8",
    slug: "panno-effecta-jungle-beige",
    brand: "Cersanit",
    collection: "Effecta",
    product_type: "Настенное панно",
    format: "60x60",
    surface: "глянцевая",
    color: "бежевый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 665.34,
    price_official: 627.48,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/20f/ECL011.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/20f/ECL011.jpg",
      "https://pvi.cersanit.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
      "https://pvi.cersanit.ru/upload/uf/580/INT_Effecta_jungle_1_3.jpg"
    ],
    stock_yanino: 42,
    stock_factory: 150,
    rating: 4.9,
    reviews_count: 28,
    rooms: ["Ванная комната"]
  },
  {
    id: "A15925",
    sku: "15925",
    name: "Настенная вставка Calacatta шеврон белый 29,8x59,8",
    slug: "vstavka-calacatta-chevron-white",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 678.66,
    price_official: 640.87,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3e2/KTL051.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3e2/KTL051.jpg",
      "https://pvi.cersanit.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/fa4/INT_Calacatta_2_2.jpg"
    ],
    stock_yanino: 65,
    stock_factory: 180,
    rating: 4.7,
    reviews_count: 22,
    rooms: ["Ванная комната"]
  },
  {
    id: "WN4T013",
    sku: "15971",
    name: "Глаз. керамогранит Wood Concept Natural бежевый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-beige",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/4af/15971_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/02e/Interior_WN4T013_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/4af/15971_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/02e/Interior_WN4T013_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/320/Interior_WN4T013_3.jpg"
    ],
    stock_yanino: 215,
    stock_factory: 560,
    rating: 4.9,
    reviews_count: 67,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "WN4T103",
    sku: "15973",
    name: "Глаз. керамогранит Wood Concept Natural песочный рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-sand",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "песочный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/05e/15973_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/2be/Interior_WN4T103_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/05e/15973_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/2be/Interior_WN4T103_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/045/Interior_WN4T103_3.jpg"
    ],
    stock_yanino: 180,
    stock_factory: 500,
    rating: 4.8,
    reviews_count: 54,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "WN4T113",
    sku: "15975",
    name: "Глаз. керамогранит Wood Concept Natural коричневый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-brown",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/01e/15975_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/815/Interior_WN4T113_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/01e/15975_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/815/Interior_WN4T113_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/252/Interior_WN4T113_2.jpg"
    ],
    stock_yanino: 195,
    stock_factory: 480,
    rating: 4.9,
    reviews_count: 71,
    rooms: ["Гостиная", "Кухня"]
  },
  {
    id: "WN4T303",
    sku: "15977",
    name: "Глаз. керамогранит Wood Concept Natural светло-бежевый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-light-beige",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/9ef/15977_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3fd/Interior_WN4T303_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/9ef/15977_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3fd/Interior_WN4T303_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/bb9/Interior_WN4T303_2.jpg"
    ],
    stock_yanino: 170,
    stock_factory: 450,
    rating: 4.7,
    reviews_count: 48,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "WP4T093",
    sku: "15979",
    name: "Глаз. керамогранит Wood Concept Prime серый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-prime-grey",
    brand: "Cersanit",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/0d5/16021_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/295/Interior_WP4T093_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/0d5/16021_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/295/Interior_WP4T093_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/2e0/Interior_WP4T093_2.jpg"
    ],
    stock_yanino: 205,
    stock_factory: 520,
    rating: 4.8,
    reviews_count: 59,
    rooms: ["Гостиная", "Кухня"]
  },
  {
    id: "WP4T523",
    sku: "15981",
    name: "Глаз. керамогранит Wood Concept Prime светло-серый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-prime-light-grey",
    brand: "Cersanit",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/af4/15981_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/8e6/Interior_WP4T523_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/af4/15981_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/8e6/Interior_WP4T523_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/9df/Interior_WP4T523_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/3d5/INT_WP4T523_3_2.jpg"
    ],
    stock_yanino: 220,
    stock_factory: 580,
    rating: 4.9,
    reviews_count: 83,
    rooms: ["Гостиная", "Кухня"]
  },
  {
    id: "WR4T013",
    sku: "15983",
    name: "Глаз. керамогранит Wood Concept Rustic бежевый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-rustic-beige",
    brand: "Cersanit",
    collection: "Wood Concept Rustic",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/039/15983_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/581/Interior_WR4T013_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/039/15983_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/581/Interior_WR4T013_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/67f/Interior_WR4T013_2.jpg"
    ],
    stock_yanino: 185,
    stock_factory: 490,
    rating: 4.8,
    reviews_count: 62,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "A15985",
    sku: "15985",
    name: "Глаз. керамогранит Wood Concept Natural темно-коричневый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-dark-brown",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "темно-коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d0c/15985_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/58c/INT_15985_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d0c/15985_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/58c/INT_15985_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d0f/INT_15985_2.jpg"
    ],
    stock_yanino: 165,
    stock_factory: 440,
    rating: 4.7,
    reviews_count: 51,
    rooms: ["Гостиная", "Спальня"]
  },
  {
    id: "A15987",
    sku: "15987",
    name: "Глаз. керамогранит Wood Concept Natural светло-коричневый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-light-brown",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/f5e/15987_10.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/bf9/INT_15987_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/f5e/15987_10.jpg",
      "https://pvi.cersanit.ru/upload/uf/bf9/INT_15987_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/c9f/INT_15987_2.jpg"
    ],
    stock_yanino: 190,
    stock_factory: 510,
    rating: 4.8,
    reviews_count: 57,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "A15989",
    sku: "15989",
    name: "Глаз. керамогранит Wood Concept Prime белый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-prime-white",
    brand: "Cersanit",
    collection: "Wood Concept Prime",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.83,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/99e/15989_10.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/9e4/INT_15989_01.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/99e/15989_10.jpg",
      "https://pvi.cersanit.ru/upload/uf/9e4/INT_15989_01.jpg",
      "https://pvi.cersanit.ru/upload/uf/644/INT_15989_02.jpg"
    ],
    stock_yanino: 210,
    stock_factory: 550,
    rating: 4.9,
    reviews_count: 76,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "A16040",
    sku: "16040",
    name: "Настенная мозаика Royal stone белый 30x30",
    slug: "mozaika-royal-stone-white",
    brand: "Cersanit",
    collection: "Royal stone",
    product_type: "Мозаика на сетке",
    format: "30x30",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 630,
    price_official: 596.16,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/8df/16040.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/955/INT_Royal_Stone_OR_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/8df/16040.jpg",
      "https://pvi.cersanit.ru/upload/uf/955/INT_Royal_Stone_OR_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/104/INT_Royal_Stone_OR_3_3.jpg"
    ],
    stock_yanino: 95,
    stock_factory: 280,
    rating: 4.7,
    reviews_count: 34,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "AN4R012",
    sku: "16087",
    name: "Глаз. керамогранит Atria бежевый 42x42",
    slug: "keramogranit-atria-beige",
    brand: "Cersanit",
    collection: "Atria",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,85",
    price_retail: 1360,
    price_official: 1325.30,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d77/Atria_42x42_AN4R012_floor_jpg.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/122/INT_Atria_Abstract_2_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d77/Atria_42x42_AN4R012_floor_jpg.jpg",
      "https://pvi.cersanit.ru/upload/uf/122/INT_Atria_Abstract_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/466/Atria_20x44_2_int_jpg.jpg"
    ],
    stock_yanino: 140,
    stock_factory: 380,
    rating: 4.6,
    reviews_count: 41,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "CO4L012",
    sku: "16292",
    name: "Глаз. керамогранит Coliseum бежевый рельеф 29,7x59,8",
    slug: "keramogranit-coliseum-beige",
    brand: "Cersanit",
    collection: "Coliseum",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e34/C_CO4L012D_1f.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/93e/INT_Coliseum_012_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e34/C_CO4L012D_1f.jpg",
      "https://pvi.cersanit.ru/upload/uf/93e/INT_Coliseum_012_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ab6/INT_Coliseum_012_2_2.jpg"
    ],
    stock_yanino: 175,
    stock_factory: 460,
    rating: 4.7,
    reviews_count: 49,
    rooms: ["Гостиная", "Спальня"]
  },
  {
    id: "GA4L012",
    sku: "16298",
    name: "Глаз. керамогранит Galaxy бежевый рельеф 29,7x59,8",
    slug: "keramogranit-galaxy-beige",
    brand: "Cersanit",
    collection: "Galaxy",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/857/GA4L012_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/279/Int_Galaxy_012_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/857/GA4L012_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/279/Int_Galaxy_012_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/bd5/Int_Galaxy_012_1_3.jpg"
    ],
    stock_yanino: 155,
    stock_factory: 420,
    rating: 4.8,
    reviews_count: 55,
    rooms: ["Ванная комната"]
  },
  {
    id: "GA4L452",
    sku: "16300",
    name: "Глаз. керамогранит Galaxy многоцветный рельеф 29,7x59,8",
    slug: "keramogranit-galaxy-multicolor",
    brand: "Cersanit",
    collection: "Galaxy",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "многоцветный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/dbc/GA4L452_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/5bd/Int_Galaxy_452_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/dbc/GA4L452_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/5bd/Int_Galaxy_452_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e6/Int_Galaxy_452_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/c49/Int_Galaxy_452_1_3.jpg"
    ],
    stock_yanino: 132,
    stock_factory: 365,
    rating: 4.7,
    reviews_count: 42,
    rooms: ["Гостиная", "Кухня"]
  },
  {
    id: "IN4L092",
    sku: "16302",
    name: "Глаз. керамогранит Infinity серый рельеф 29,7x59,8",
    slug: "keramogranit-infinity-grey",
    brand: "Cersanit",
    collection: "Infinity",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/841/IN4L092_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/672/INT_Infinity_092_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/841/IN4L092_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/672/INT_Infinity_092_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3b9/INT_Infinity_092_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/ee9/INT_Infinity_092_1_3.jpg"
    ],
    stock_yanino: 168,
    stock_factory: 445,
    rating: 4.8,
    reviews_count: 58,
    rooms: ["Ванная комната", "Коридор"]
  },
  {
    id: "IN4L402",
    sku: "16304",
    name: "Глаз. керамогранит Infinity темно-серый рельеф 29,7x59,8",
    slug: "keramogranit-infinity-dark-grey",
    brand: "Cersanit",
    collection: "Infinity",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "темно-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/782/IN4L402_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/6e7/INT_Infinity_402_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/782/IN4L402_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/6e7/INT_Infinity_402_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/af2/INT_Infinity_402_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/aa9/INT_Infinity_402_1_3.jpg"
    ],
    stock_yanino: 142,
    stock_factory: 390,
    rating: 4.9,
    reviews_count: 65,
    rooms: ["Гостиная", "Спальня"]
  },
  {
    id: "LS4O522",
    sku: "16310",
    name: "Глаз. керамогранит Lofthouse светло-серый рельеф 29,7x59,8",
    slug: "keramogranit-lofthouse-light-grey",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "светло-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d3c/C_LS4L522D_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/79d/1_32_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d3c/C_LS4L522D_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/79d/1_32_.jpg",
      "https://pvi.cersanit.ru/upload/uf/a8c/3_1_.jpg"
    ],
    stock_yanino: 195,
    stock_factory: 515,
    rating: 4.8,
    reviews_count: 71,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "LS4O092",
    sku: "16312",
    name: "Глаз. керамогранит Lofthouse серый рельеф 29,7x59,8",
    slug: "keramogranit-lofthouse-grey",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/eef/C_LS4L092D_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/5d0/1_39_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/eef/C_LS4L092D_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/5d0/1_39_.jpg",
      "https://pvi.cersanit.ru/upload/uf/3fb/INT_Lofthouse_Mix_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d5b/INT_Lofthouse_Mix_2_2.jpg"
    ],
    stock_yanino: 210,
    stock_factory: 560,
    rating: 4.9,
    reviews_count: 89,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "A15886",
    sku: "16316",
    name: "Глаз. керамогранит Lorenzo белый 29,7x59,8",
    slug: "keramogranit-lorenzo-white",
    brand: "Cersanit",
    collection: "Lorenzo",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/877/15886_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/eb1/Lorenzo_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/877/15886_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/eb1/Lorenzo_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ad3/Lorenzo_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/474/Lorenzo_1_3.jpg"
    ],
    stock_yanino: 225,
    stock_factory: 590,
    rating: 4.9,
    reviews_count: 102,
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "MU4L012",
    sku: "16318",
    name: "Глаз. керамогранит Mercury бежевый рельеф 29,7x59,8",
    slug: "keramogranit-mercury-beige",
    brand: "Cersanit",
    collection: "Mercury",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3b6/MU4L012_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ac4/INT_Mercury_012_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3b6/MU4L012_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ac4/INT_Mercury_012_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/5d7/INT_Mercury_012_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae4/INT_Mercury_012_1_3.jpg"
    ],
    stock_yanino: 158,
    stock_factory: 425,
    rating: 4.7,
    reviews_count: 53,
    rooms: ["Ванная комната", "Балкон"]
  },
  {
    id: "MU4L092",
    sku: "16320",
    name: "Глаз. керамогранит Mercury серый рельеф 29,7x59,8",
    slug: "keramogranit-mercury-grey",
    brand: "Cersanit",
    collection: "Mercury",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/44a/MU4L092_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/99f/INT_Mercury_092_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/44a/MU4L092_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/99f/INT_Mercury_092_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/744/INT_Mercury_092_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/bc7/INT_Mercury_092_1_3.jpg"
    ],
    stock_yanino: 172,
    stock_factory: 460,
    rating: 4.8,
    reviews_count: 61,
    rooms: ["Балкон", "Терраса"]
  },
  {
    id: "OB4L112",
    sku: "16322",
    name: "Глаз. керамогранит Orion коричневый 29,7x59,8",
    slug: "keramogranit-orion-brown",
    brand: "Cersanit",
    collection: "Orion",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/7f0/C_OB4L112D_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f9b/INT_Orion_112_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/7f0/C_OB4L112D_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/f9b/INT_Orion_112_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/9c7/INT_Orion_112_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/795/INT_Orion_112_2_3.jpg"
    ],
    stock_yanino: 145,
    stock_factory: 395,
    rating: 4.6,
    reviews_count: 47,
    rooms: ["Коридор", "Балкон", "Терраса"]
  },
  {
    id: "OB4L092",
    sku: "16324",
    name: "Глаз. керамогранит Orion серый 29,7x59,8",
    slug: "keramogranit-orion-grey",
    brand: "Cersanit",
    collection: "Orion",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/688/C_OB4L092D_1f.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/81c/INT_Orion_092_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/688/C_OB4L092D_1f.jpg",
      "https://pvi.cersanit.ru/upload/uf/81c/INT_Orion_092_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/250/INT_Orion_092_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/484/INT_Orion_092_2_3.jpg"
    ],
    stock_yanino: 163,
    stock_factory: 440,
    rating: 4.7,
    reviews_count: 56,
    rooms: ["Коридор", "Терраса"]
  },
  {
    id: "PG4L522",
    sku: "16328",
    name: "Глаз. керамогранит Polaris светло-серый 29,7x59,8",
    slug: "keramogranit-polaris-light-grey",
    brand: "Cersanit",
    collection: "Polaris",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "светло-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/986/C_PG4L522D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/67e/INT_Polaris_522_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/986/C_PG4L522D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/67e/INT_Polaris_522_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/52b/INT_Polaris_522_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/e61/INT_Polaris_522_2_3.jpg"
    ],
    stock_yanino: 188,
    stock_factory: 505,
    rating: 4.8,
    reviews_count: 73,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "PG4L092",
    sku: "16330",
    name: "Глаз. керамогранит Polaris серый 29,7x59,8",
    slug: "keramogranit-polaris-grey",
    brand: "Cersanit",
    collection: "Polaris",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/c17/C_PG4L092D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/088/INT_Polaris_092_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/c17/C_PG4L092D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/088/INT_Polaris_092_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/cb4/INT_Polaris_092_3_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/d48/INT_Polaris_092_3_3.jpg"
    ],
    stock_yanino: 175,
    stock_factory: 475,
    rating: 4.7,
    reviews_count: 64,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "PG4L402",
    sku: "16332",
    name: "Глаз. керамогранит Polaris темно-серый 29,7x59,8",
    slug: "keramogranit-polaris-dark-grey",
    brand: "Cersanit",
    collection: "Polaris",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "темно-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/a06/C_PG4L402D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/067/INT_Polaris_402_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/a06/C_PG4L402D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/067/INT_Polaris_402_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/b02/INT_Polaris_402_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/803/INT_Antiquewood_092_Polaris_402.jpg"
    ],
    stock_yanino: 152,
    stock_factory: 410,
    rating: 4.8,
    reviews_count: 59,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "SF4L402",
    sku: "16334",
    name: "Глаз. керамогранит Slate темно-серый рельеф 29,7x59,8",
    slug: "keramogranit-slate-dark-grey",
    brand: "Cersanit",
    collection: "Slate",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "темно-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/875/C_SF4L402D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/472/Slate_30x60x_int_2_jpg (1).jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/875/C_SF4L402D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/472/Slate_30x60x_int_2_jpg (1).jpg",
      "https://pvi.cersanit.ru/upload/uf/65a/Slate_30x60_int_3_jpg.jpg",
      "https://pvi.cersanit.ru/upload/uf/71b/INT_Slate_6_1.jpg"
    ],
    stock_yanino: 138,
    stock_factory: 380,
    rating: 4.9,
    reviews_count: 78,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "SC4L092",
    sku: "16336",
    name: "Глаз. керамогранит Space серый 29,7x59,8",
    slug: "keramogranit-space-grey",
    brand: "Cersanit",
    collection: "Space",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/ba2/SC4L092_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/7e4/Int_Space_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/ba2/SC4L092_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/7e4/Int_Space_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/bc5/Int_Space_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/474/Int_Space_1_3.jpg"
    ],
    stock_yanino: 198,
    stock_factory: 535,
    rating: 4.9,
    reviews_count: 94,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "WS4O112",
    sku: "16346",
    name: "Глаз. керамогранит Woodhouse коричневый рельеф 29,7x59,8",
    slug: "keramogranit-woodhouse-brown",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/038/C_WS4L112D_k1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/038/C_WS4L112D_k1.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/6c3/INT_Woodhouse_WS4O112_3_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/1cf/INT_Woodhouse_WS4O112_3_3.jpg"
    ],
    stock_yanino: 185,
    stock_factory: 495,
    rating: 4.8,
    reviews_count: 68,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "WS4O522",
    sku: "16350",
    name: "Глаз. керамогранит Woodhouse светло-серый рельеф 29,7x59,8",
    slug: "keramogranit-woodhouse-light-grey",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "светло-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d7f/C_WS4L522D_2.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/aea/PC_005.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d7f/C_WS4L522D_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/aea/PC_005.jpg",
      "https://pvi.cersanit.ru/upload/uf/8de/PC_007_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/da6/PC_007.jpg"
    ],
    stock_yanino: 203,
    stock_factory: 545,
    rating: 4.9,
    reviews_count: 81,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "WS4O152",
    sku: "16354",
    name: "Глаз. керамогранит Woodhouse темно-бежевый рельеф 29,7x59,8",
    slug: "keramogranit-woodhouse-dark-beige",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "матовая",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.94,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/390/C_WS4L152D_k1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/a54/Woodhouse_DARK_BEIGE_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/390/C_WS4L152D_k1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a54/Woodhouse_DARK_BEIGE_1.jpg"
    ],
    stock_yanino: 167,
    stock_factory: 445,
    rating: 4.7,
    reviews_count: 52,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "A16521",
    sku: "16521",
    name: "Глаз. керамогранит Mont Blanc белый 29,7x59,8",
    slug: "keramogranit-mont-blanc-white",
    brand: "Cersanit",
    collection: "Mont Blanc",
    product_type: "Керамогранит",
    format: "30x60",
    surface: "сатиновая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,75",
    price_retail: 1035,
    price_official: 1000.98,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/files/get/11/21816/29905/800/800/0/",
    collection_image: "https://pvi.cersanit.ru/files/get/11/21816/29923/800/800/0/",
    images: [
      "https://pvi.cersanit.ru/files/get/11/21816/29905/800/800/0/",
      "https://pvi.cersanit.ru/files/get/11/21816/29923/800/800/0/",
      "https://pvi.cersanit.ru/files/get/11/21816/29925/800/800/0/"
    ],
    stock_yanino: 215,
    stock_factory: 575,
    rating: 4.9,
    reviews_count: 96,
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня"]
  }
];
