// Additional products batch - will be merged into main file
export const additionalProducts = [
  {
    id: "A16004",
    sku: "17194",
    name: "Глаз. керамогранит Oriental серый 42x42",
    slug: "keramogranit-oriental-grey",
    brand: "Cersanit",
    collection: "Oriental",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/4e5/16004_10.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/d65/INT_Oriental-_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/4e5/16004_10.jpg",
      "https://pvi.cersanit.ru/upload/uf/d65/INT_Oriental-_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/7b3/INT_Oriental_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/bd2/INT_Oriental_2_3.jpg"
    ],
    stock_yanino: 142,
    stock_factory: 385,
    rating: 4.7,
    reviews_count: 56,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "A16002",
    sku: "17196",
    name: "Глаз. керамогранит Oriental черный 42x42",
    slug: "keramogranit-oriental-black",
    brand: "Cersanit",
    collection: "Oriental",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "черный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e02/16002_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/d65/INT_Oriental-_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e02/16002_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d65/INT_Oriental-_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a7b/INT_Oriental_1_2.jpg"
    ],
    stock_yanino: 128,
    stock_factory: 350,
    rating: 4.8,
    reviews_count: 68,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "PW4R052",
    sku: "17198",
    name: "Глаз. керамогранит Palitra белый 42x42",
    slug: "keramogranit-palitra-white",
    brand: "Cersanit",
    collection: "Palitra",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e44/Palitra_42x42_PW4R052_floor_jpg.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/e54/Palitra_42x42_int_jpg.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e44/Palitra_42x42_PW4R052_floor_jpg.jpg",
      "https://pvi.cersanit.ru/upload/uf/e54/Palitra_42x42_int_jpg.jpg",
      "https://pvi.cersanit.ru/upload/uf/7b1/INT_Palitra_2_1.jpg"
    ],
    stock_yanino: 185,
    stock_factory: 500,
    rating: 4.9,
    reviews_count: 95,
    rooms: ["Коридор", "Кухня", "Балкон"]
  },
  {
    id: "PD4R452",
    sku: "17206",
    name: "Глаз. керамогранит Pudra многоцветный 42x42",
    slug: "keramogranit-pudra-multicolor",
    brand: "Cersanit",
    collection: "Pudra",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "многоцветный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/6c7/C_PD4R452D.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/eeb/INT_Pudra_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/6c7/C_PD4R452D.jpg",
      "https://pvi.cersanit.ru/upload/uf/eeb/INT_Pudra_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/05e/INT_Pudra_3_1.jpg"
    ],
    stock_yanino: 95,
    stock_factory: 255,
    rating: 4.6,
    reviews_count: 42,
    rooms: ["Коридор", "Кухня"]
  },
  {
    id: "QN4R053",
    sku: "17208",
    name: "Глаз. керамогранит Queen белый 42x42",
    slug: "keramogranit-queen-white",
    brand: "Cersanit",
    collection: "Queen",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/2ab/QN4R053_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/968/INT_Queen_053_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/2ab/QN4R053_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/968/INT_Queen_053_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/2b7/INT_Queen_053_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/647/INT_Queen_053_2_3.jpg"
    ],
    stock_yanino: 215,
    stock_factory: 575,
    rating: 4.9,
    reviews_count: 122,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "QN4R233",
    sku: "17210",
    name: "Глаз. керамогранит Queen черный 42x42",
    slug: "keramogranit-queen-black",
    brand: "Cersanit",
    collection: "Queen",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "черный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/007/QN4R233_5.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/548/INT_Queen_233_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/007/QN4R233_5.jpg",
      "https://pvi.cersanit.ru/upload/uf/548/INT_Queen_233_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a6a/INT_Queen_233_2_2.jpg"
    ],
    stock_yanino: 198,
    stock_factory: 535,
    rating: 4.9,
    reviews_count: 135,
    rooms: ["Гостиная", "Спальня", "Кухня"]
  },
  {
    id: "RE4R092",
    sku: "17214",
    name: "Глаз. керамогранит Raven серый 42x42",
    slug: "keramogranit-raven-grey",
    brand: "Cersanit",
    collection: "Raven",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/366/C_RE4R092D_k1_jpeg.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/352/RAVEN_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/366/C_RE4R092D_k1_jpeg.jpg",
      "https://pvi.cersanit.ru/upload/uf/352/RAVEN_1.jpg"
    ],
    stock_yanino: 165,
    stock_factory: 445,
    rating: 4.8,
    reviews_count: 78,
    rooms: ["Гостиная", "Спальня", "Кухня", "Коридор"]
  },
  {
    id: "RS4R052",
    sku: "17216",
    name: "Глаз. керамогранит Royal Stone белый 42x42",
    slug: "keramogranit-royal-stone-white-42x42",
    brand: "Cersanit",
    collection: "Royal Stone",
    product_type: "Керамогранит",
    format: "42x42",
    surface: "матовая",
    color: "белый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1370,
    price_official: 1313.73,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77d/RS4R052D_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77d/RS4R052D_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/299/INT_Royal_stone_2_2.jpg"
    ],
    stock_yanino: 235,
    stock_factory: 630,
    rating: 4.9,
    reviews_count: 148,
    rooms: ["Ванная комната", "Гостиная", "Спальня", "Кухня", "Коридор"]
  }
];
