// Auto-generated from CSV import - All Cersanit products
// Total products: 203

export interface Product {
  id: string
  sku?: string
  name: string
  slug?: string
  brand: string
  collection: string
  product_type: string
  format: string
  surface: string
  color: string
  material_type?: string
  application: string
  width?: string
  length?: string
  thickness?: string
  pieces_per_box?: number
  sqm_per_box?: number
  country?: string
  price_retail: number
  price_official?: number | null
  currency?: string
  stock_yanino?: number
  stock_factory?: number
  description?: string
  images?: string[]
  main_image?: string
  collection_image?: string
  interior_image?: string | null
  is_new?: boolean
  is_bestseller?: boolean
  is_discount?: boolean
  rating?: number
  reviews_count?: number
  rooms?: string[]
}

export const products: Product[] = [
  {
    id: "LS4O096",
    sku: "A-LS4O096\\J",
    name: "Ступень Cersanit Lofthouse  серый  29,7x59,8 LS4O096",
    slug: "stepen-lofthouse-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    sqm_per_box: undefined,
    price_retail: 1450,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg"],
    stock_yanino: 150,
    stock_factory: 300,
    rating: 4.7,
    reviews_count: 24
  },
  {
    id: "LS4O526",
    sku: "A-LS4O526\\J",
    name: "Ступень Cersanit Lofthouse  светло-серый  29,7x59,8 LS4O526",
    slug: "stepen-lofthouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    price_retail: 1480,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg"],
    stock_yanino: 120,
    stock_factory: 280,
    rating: 4.6,
    reviews_count: 18
  },
  {
    id: "LS5A096",
    sku: "A-LS5A096\\J",
    name: "Плинтус Cersanit Lofthouse  серый  7x59,8 LS5A096",
    slug: "plintus-lofthouse-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 420,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg"],
    stock_yanino: 200,
    stock_factory: 400,
    rating: 4.8,
    reviews_count: 32
  },
  {
    id: "LS5A526",
    sku: "A-LS5A526\\J",
    name: "Плинтус Cersanit Lofthouse  светло-серый  7x59,8 LS5A526",
    slug: "plintus-lofthouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 410,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg"],
    stock_yanino: 180,
    stock_factory: 380,
    rating: 4.7,
    reviews_count: 28
  },
  {
    id: "LS6O096",
    sku: "A-LS6O096\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  серый  28,3x24,6 LS6O096",
    slug: "mozaika-lofthouse-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1680,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
      "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ed3/INT_LOFTHOUSE_5_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/5aa/INT_LOFTHOUSE_5_4.jpg",
      "https://pvi.cersanit.ru/upload/uf/b7f/INT_LOFTHOUSE_5_5.jpg"
    ],
    stock_yanino: 95,
    stock_factory: 220,
    rating: 4.9,
    reviews_count: 41
  },
  {
    id: "LS6O526",
    sku: "A-LS6O526\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  светло-серый  28,3x24,6 LS6O526",
    slug: "mozaika-lofthouse-svetlo-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1710,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg"
    ],
    stock_yanino: 87,
    stock_factory: 195,
    rating: 4.8,
    reviews_count: 35
  },
  {
    id: "RS2L451",
    sku: "A-RS2L451\\G",
    name: "Мозаика на сетке Cersanit Royal Stone  многоцветный  30x30 RS2L451",
    slug: "mozaika-royal-stone-mnogotsvetnyi-30x30",
    brand: "Cersanit",
    collection: "Royal Stone",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "многоцветный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "1",
    pieces_per_box: 17,
    price_retail: 1820,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
      "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/299/INT_Royal_stone_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/976/INT_Royal_stone_2_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/cae/Royal_Stone.jpg"
    ],
    stock_yanino: 76,
    stock_factory: 160,
    rating: 4.9,
    reviews_count: 48
  },
  {
    id: "WS4O116",
    sku: "A-WS4O116\\J",
    name: "Ступень Cersanit Woodhouse  коричневый  29,7x59,8 WS4O116",
    slug: "stepen-woodhouse-korichnevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1520,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1cf/INT_Woodhouse_WS4O112_3_3.jpg"
    ],
    stock_yanino: 142,
    stock_factory: 310,
    rating: 4.8,
    reviews_count: 29
  },
  {
    id: "WS4O156",
    sku: "A-WS4O156\\J",
    name: "Ступень Cersanit Woodhouse  темно-бежевый  29,7x59,8 WS4O156",
    slug: "stepen-woodhouse-temno-bezhevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1490,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg"],
    stock_yanino: 128,
    stock_factory: 295,
    rating: 4.7,
    reviews_count: 22
  },
  {
    id: "WS4O526",
    sku: "A-WS4O526\\J",
    name: "Ступень Cersanit Woodhouse  светло-серый  29,7x59,8 WS4O526",
    slug: "stepen-woodhouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    price_retail: 1510,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 155,
    stock_factory: 320,
    rating: 4.9,
    reviews_count: 36
  },
  {
    id: "WS5A116",
    sku: "A-WS5A116\\J",
    name: "Плинтус Cersanit Woodhouse  коричневый  7x59,8 WS5A116",
    slug: "plintus-woodhouse-korichnevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 430,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg"],
    stock_yanino: 215,
    stock_factory: 430,
    rating: 4.6,
    reviews_count: 19
  },
  {
    id: "WS5A156",
    sku: "A-WS5A156\\J",
    name: "Плинтус Cersanit Woodhouse  темно-бежевый  7x59,8 WS5A156",
    slug: "plintus-woodhouse-temno-bezhevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 445,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg"],
    stock_yanino: 192,
    stock_factory: 405,
    rating: 4.7,
    reviews_count: 25
  },
  {
    id: "WS5A526",
    sku: "A-WS5A526\\J",
    name: "Плинтус Cersanit Woodhouse  светло-серый  7x59,8 WS5A526",
    slug: "plintus-woodhouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    price_retail: 435,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 203,
    stock_factory: 418,
    rating: 4.8,
    reviews_count: 31
  },
  {
    id: "WS6O116",
    sku: "A-WS6O116\\J",
    name: "Мозаика на сетке Cersanit Woodhouse  коричневый  30x30 WS6O116",
    slug: "mozaika-woodhouse-korichnevyi-30x30",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "0,95",
    pieces_per_box: 10,
    price_retail: 1750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3fb/INT_Lofthouse_Mix_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d5b/INT_Lofthouse_Mix_2_2.jpg"
    ],
    stock_yanino: 88,
    stock_factory: 178,
    rating: 4.9,
    reviews_count: 44
  },
  {
    id: "NW4M012",
    sku: "C-NW4M012D",
    name: "Керамогранит Cersanit Northwood  бежевый  18,5x59,8 NW4M012",
    slug: "keramogranit-northwood-bezhevyi-18x60",
    brand: "Cersanit",
    collection: "Northwood",
    product_type: "Керамогранит",
    format: "18x60",
    color: "бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "18,5",
    length: "59,8",
    thickness: "0,85",
    pieces_per_box: 9,
    sqm_per_box: 0.99,
    price_retail: 890,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1f6/INT_Northwood_012_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a08/INT_Northwood_012_2_2.jpg"
    ],
    stock_yanino: 245,
    stock_factory: 520,
    rating: 4.8,
    reviews_count: 37,
    rooms: ["Кухня", "Коридор", "Балконы"]
  },
  {
    id: "DE2L381",
    sku: "DE2L381DT-36",
    name: "Настенная вставка Cersanit Deco орнамент золотистый  29,8x59,8 DE2L381",
    slug: "vstavka-deco-ornament-zolotistyi-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "золотистый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    price_retail: 1620,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/25b/Deco_Large_2.jpg"
    ],
    stock_yanino: 67,
    stock_factory: 142,
    rating: 4.9,
    reviews_count: 52,
    is_new: true
  },
  {
    id: "DEL232",
    sku: "DEL232D-60",
    name: "Плитка Cersanit Deco  черный  рельеф  29,8x59,8 DEL232",
    slug: "plitka-deco-chernyi-relef-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Плитка",
    format: "30x60",
    color: "черный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg"
    ],
    stock_yanino: 188,
    stock_factory: 395,
    rating: 4.7,
    reviews_count: 26,
    rooms: ["Ванная комната", "Гостиная", "Спальня"]
  },
  {
    id: "KT2L051",
    sku: "KT2L051DT-36",
    name: "Настенная вставка Cersanit Calacatta узор белый  29,8x59,8 KT2L051",
    slug: "vstavka-calacatta-uzor-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    price_retail: 1580,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg"
    ],
    stock_yanino: 72,
    stock_factory: 158,
    rating: 4.9,
    reviews_count: 47,
    is_bestseller: true
  },
  {
    id: "KTL051",
    sku: "KTL051D-60",
    name: "Плитка Cersanit Calacatta  белый  29,8x59,8 KTL051",
    slug: "plitka-calacatta-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 780,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 210,
    stock_factory: 445,
    rating: 4.8,
    reviews_count: 38,
    rooms: ["Ванная комната", "Гостиная"],
    is_bestseller: true
  },
  {
    id: "KTL052",
    sku: "KTL052D-60",
    name: "Плитка Cersanit Calacatta  белый  рельеф  29,8x59,8 KTL052",
    slug: "plitka-calacatta-belyi-relef-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 795,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 198,
    stock_factory: 420,
    rating: 4.7,
    reviews_count: 33,
    rooms: ["Ванная комната", "Спальня"]
  }
];
